# Generated by Django 3.2.8 on 2021-10-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_auto_20211023_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riddle',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
