# Generated by Django 3.2.8 on 2021-10-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0004_alter_riddle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
