# Generated by Django 3.2.8 on 2021-10-26 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0007_auto_20211025_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 12, 19, 914478)),
        ),
        migrations.CreateModel(
            name='RightAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightanswers', models.TextField(null=True)),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.riddle')),
            ],
            options={
                'verbose_name': 'Правильный ответ на вопрос',
                'verbose_name_plural': 'Правильные ответы на вопросы',
            },
        ),
    ]
