# Generated by Django 3.2.8 on 2021-10-28 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0008_auto_20211026_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='name',
        ),
        migrations.AddField(
            model_name='riddle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Задаваемый вопрос'),
        ),
        migrations.AddField(
            model_name='riddle',
            name='day_filter',
            field=models.CharField(default='1', max_length=2, verbose_name='На какой день вопрос'),
        ),
        migrations.AddField(
            model_name='riddle',
            name='image',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 20, 38, 54, 310375)),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='riddle_text',
            field=models.CharField(max_length=255, verbose_name='Текст вопроса'),
        ),
        migrations.DeleteModel(
            name='RightAnswers',
        ),
    ]
