# Generated by Django 3.2.8 on 2021-10-29 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0009_auto_20211028_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 18, 47, 54, 615698)),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Картинка'),
        ),
    ]
