# Generated by Django 3.2.8 on 2021-10-29 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0011_auto_20211029_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 22, 28, 10, 510951)),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='image',
            field=models.ImageField(blank=True, upload_to='static', verbose_name='Картинка'),
        ),
    ]
